language: android
sudo: required
dist: trusty

jdk:
  - oraclejdk8

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

android:
  components:
    - tools
    - build-tools-26.0.0
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
