language: android
sudo: required
dist: trusty

jdk:
  - oraclejdk8

script:
  - ./gradlew test -i
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

android:
  components:
        - tools
        - platform-tools
        - tools
        - build-tools-25.0.2
        - android-25
